main: fr.aang.gcity.Main
name: GCity
version: 1.0
api-version: 1.19
depend: [ Vault, Multiverse-Core ]
author: [ Aang ]
commands:
  city:
    description: Gere les parcelles joueurs
permissions:
  gcity.use:
    description: Autorise tout
    default: op